theme: minima
title: Dave's awesome title
author: Dave
email: my-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  It's gonna be awesome. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: StandupTweets # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
